version: "3.9"

services:
  service1:
    image: microservice_gateway:latest # Tag of the built image used for Service1
    build: ./service1 # Path to the Dockerfile for building the image
    ports:
      - "8199:8199"   # only service1 exposed
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - service2
      - storage

  service2:
    image: microservice_worker:latest # Tag of the built image used for Service2
    build: ./service2
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - storage

  storage:
    image: microservice_storage:latest # Tag of the built image used for Storage
    build: ./storage
    networks:
      - appnet
    volumes:
      - storage_data:/data

volumes:
  storage_data:

networks:
  appnet:
    driver: bridge
