version: "3.9"

services:
  service1:
    image: microservice_gateway:latest
    build: ./service1
    ports:
      - "8199:8199"   # only service1 exposed
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - service2
      - storage

  service2:
    image: microservice_worker:latest
    build: ./service2
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - storage

  storage:
    image: microservice_storage:latest
    build: ./storage
    networks:
      - appnet
    volumes:
      - storage_data:/data

volumes:
  storage_data:

networks:
  appnet:
    driver: bridge
